title: healthy Project
description: Proyecto de arcade retro hecho en madera
baseurl: "/by-endulzartes"  # Asegúrate de que esto coincida con tu repositorio en GitHub Pages
url: "https://healthydelicias.github.io"  # Tu URL de GitHub Pages
theme: jekyll-theme-primer
